### ISSUE TITLE
`users.get_by_*` return data and multiple arguments

### ISSUE THREAD

**Issue by AlexWayfer** [deanpcmad/twitchrb#4]
Hello.

Your lib seems a new one and powerful. Great.

I'm trying to start using it, but already faced with some problems.

I believe basic `users.get_by_*` should receive multiple values (of ID or usernames), as it allows Twitch API. To save rate limits, you know.

![image](https://github.com/deanpcmad/twitchrb/assets/6510020/105905f2-197d-4f8b-9da2-a2c2f8351845)

You're forcing the only one:

![image](https://github.com/deanpcmad/twitchrb/assets/6510020/0b3b35f7-57e3-4b89-a63c-6fd9403ac42e)

Also it'd be nice to return `nil` if there is no found user, in your current implementation, instead of empty `User` instance:

![image](https://github.com/deanpcmad/twitchrb/assets/6510020/25e83839-9e9d-4f48-9f70-e66a0e04187e)

But receiving and returning arrays of values will save us from this problem: outside projects just should check the returning Array for existing Users.

Do you agree with me?

**Comment by deanpcmad** [comment]
Good point, I personally had no need for grabbing multiple users but this has been added and will be in the next release :smile:

**Comment by AlexWayfer** [comment]
Honestly, this lib uses Faraday, and it could pass arguments to requests, like… OK, maybe I'll create a PR later.

But I mean: you could call:

```ruby
def users.get(ids)
  connection.get('/users', id: ids)
end

users.get(12345) # will form `/users?id=12345`
users.get([123, 456]) # will form `/users?id=123&id=456`
```

You can check it by yourself and get rid of extra logic in your library, it's up to Faraday.

**Comment by deanpcmad** [comment]
Oh that would certainly clean the code up a lot. Feel free to send a PR :) - will re-open for the mo

**Comment by deanpcmad** [comment]
I've made some changes to this. I've renamed it to a single `retrieve` method which can take an ID, many IDs, a username or many usernames.

Will push this in the next update

```
# Retrieves a user by their ID
@client.users.retrieve(id: 141981764)

# Retrieves multiple users by their IDs
# Requires an array of IDs
@client.users.retrieve(ids: [141981764, 72938118])

# Retrieves a user by their username
@client.users.retrieve(username: "twitchdev")

# Retrieves multiple users by their usernames
# Requires an array of IDs
@client.users.retrieve(usernames: ["twitchdev", "deanpcmad"])
```
